services:
  postgres:
    image: 'postgis/postgis:16-3.4'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_INITDB_ARGS=-k -E UTF8'
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db/schema-postgresql.sql:/docker-entrypoint-initdb.d/1.schema.sql:ro
      - ./src/test/resources/db/data-user.sql:/docker-entrypoint-initdb.d/2.data-user.sql:ro