server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  tomcat:
    relaxed-query-chars: "|,{,},[,]"

spring:
  config:
    import: layer-config-dev.yml
  application:
    name: Spatial Information Analysis System
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dj.gaia3d.com:25432/sias
    username: postgres
    password: postgres

search-api:
  jn-bbox: 125.0958943496122231,33.9716070112166975,127.8215384749895946,36.2986821617731721
  vworld:
    url: https://api.vworld.kr
    key: 4FA25B73-F1BA-398E-9152-0DB07832F215

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jn.sias.domain

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.SQL_SLOW: info
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace

